apiVersion: v1
kind: Service
metadata:
  name: nginx-external-name
  labels:
    app: adk-nginx
spec:
  type: ExternalName
  externalName: "www.google.com" # This will be proxied by nginx-external-name within the cluster
  selector:
    app: adk-nginx
  ports:
    - port: 9000
