apiVersion: v1
kind: Pod
metadata:
  name: adk-liveness
spec:
  containers:
    - name: adk-liveness
      image: k8s.gcr.io/busybox
      args: # Define args for the container to run
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30;
          rm -rf /tmp/healthy; sleep 600;
      livenessProbe:
        exec: # Test the liveness by executing cat command
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
