apiVersion: v1
kind: Service
metadata:
  name: nginx-node-port
  labels:
    app: adk-nginx
spec:
  type: NodePort
  selector:
    app: adk-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000 # Will default to a random port between 30000-32767, unless specified like this
