apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
  labels:
    app: adk-nginx
spec:
  type: LoadBalancer
  selector:
    app: adk-nginx
  ports:
    - port: 8081
      targetPort: 80
