apiVersion: v1
kind: Pod
metadata:
  name: adk-pvc-pod
  labels:
    name: storage
spec:
  containers:
    - image: nginx
      name: adk-pod
      command:
        - /bin/sh
        - -c
        - while true; do echo "date" >> /mnt/files/outfile; sleep 10; done
      volumeMounts:
        - name: adk-pvc
          mountPath: /mnt/files
  volumes:
    - name: adk-pvc
      persistentVolumeClaim:
        claimName: adk-pvc
